name: Playwright python

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install playwright
          pip install requests
          pip install psutil
          pip install pynput
          pip install aiohttp

      - name: Install Playwright Browsers
        run: |
          playwright install-deps
          playwright install chromium

      - name: Install tinyproxy
        run: sudo apt install tinyproxy


      
      - name: Start scripts
        run: |
          xvfb-run bash run.sh
          wait
